FROM ubuntu:latest

EXPOSE 80
WORKDIR /app

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# installing deps

RUN apt-get update
RUN apt-get install -y supervisor python3 python3-pip ipset iptables sudo nginx nodejs npm

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY langate2000-supervisor.conf /etc/supervisor/supervisord.conf

# nginx setup

COPY langate2000-nginx.conf /etc/nginx/sites-enabled/default

# netcontrol

ADD langate2000-netcontrol /app/langate2000-netcontrol

ADD langate2000-ui /app/langate2000-ui
WORKDIR /app/langate2000-ui

RUN npm install
RUN npm run-script build

# django

ADD langate /app/langate

WORKDIR /app/langate/

RUN python3 manage.py makemigrations --noinput
RUN python3 manage.py migrate --noinput

RUN python3 manage.py collectstatic --noinput
RUN echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('root', '', 'rien')" | python3 manage.py shell

CMD [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
